/**
 * @file    differential_drive_example.c
 * @brief   Closed-loop differential drive robot example
 *
 * Hardware assumed (CubeMX project):
 *   TIM2 CH1 — Left motor PWM
 *   TIM2 CH2 — Right motor PWM
 *   TIM3     — Left encoder (encoder mode)
 *   TIM4     — Right encoder (encoder mode)
 *   PA4/PA5  — Left motor direction (IN1/IN2)
 *   PB4/PB5  — Right motor direction (IN1/IN2)
 *
 * Control loop runs every 10 ms via TIM6 update interrupt.
 */

#include "robotics.h"
#include "main.h"   /* CubeMX generated handles */

/* ── HAL handles (generated by CubeMX) ───────────────────────────────────*/
extern TIM_HandleTypeDef htim2;   /* PWM */
extern TIM_HandleTypeDef htim3;   /* Left encoder */
extern TIM_HandleTypeDef htim4;   /* Right encoder */
extern TIM_HandleTypeDef htim6;   /* Control loop tick */

/* ── Library objects ──────────────────────────────────────────────────────*/
static Motor_t   left_motor, right_motor;
static Encoder_t left_enc,   right_enc;
static PID_t     left_pid,   right_pid;
static DiffDrive_t robot;

/* ── Target velocity (set from your command source) ──────────────────────*/
static volatile float g_target_v     = 0.3f;   /* m/s  */
static volatile float g_target_omega = 0.0f;   /* rad/s */

#define CONTROL_DT_S   0.01f          /* 10 ms */
#define WHEEL_RADIUS   0.033f         /* m      */
#define WHEEL_BASE     0.160f         /* m      */
#define ENCODER_CPR    1440           /* counts per rev (motor + gearbox) */
#define MAX_SPEED_MPS  0.5f

void Robot_Init(void)
{
    /* Motors ─────────────────────────────────────────────────────────────*/
    Motor_Init(&left_motor,  &htim2, TIM_CHANNEL_1,
               GPIOA, GPIO_PIN_4, GPIOA, GPIO_PIN_5);
    Motor_Init(&right_motor, &htim2, TIM_CHANNEL_2,
               GPIOB, GPIO_PIN_4, GPIOB, GPIO_PIN_5);

    Motor_SetInverted(&right_motor, true);   /* mirror wiring */

    /* Encoders ───────────────────────────────────────────────────────────*/
    Encoder_Init(&left_enc,  &htim3, ENCODER_CPR, CONTROL_DT_S);
    Encoder_Init(&right_enc, &htim4, ENCODER_CPR, CONTROL_DT_S);

    /* PID controllers ────────────────────────────────────────────────────*/
    PID_Init(&left_pid,  1.8f, 0.5f, 0.05f, CONTROL_DT_S);
    PID_Init(&right_pid, 1.8f, 0.5f, 0.05f, CONTROL_DT_S);
    PID_SetOutputLimits(&left_pid,  -100.0f, 100.0f);
    PID_SetOutputLimits(&right_pid, -100.0f, 100.0f);
    PID_SetFilterCoeff(&left_pid,  50.0f);
    PID_SetFilterCoeff(&right_pid, 50.0f);

    /* Kinematics ─────────────────────────────────────────────────────────*/
    DiffDrive_Init(&robot, WHEEL_RADIUS, WHEEL_BASE);
    DiffDrive_SetMaxSpeed(&robot, MAX_SPEED_MPS);

    /* Start 10 ms control tick timer */
    HAL_TIM_Base_Start_IT(&htim6);
}

/* Called from HAL_TIM_PeriodElapsedCallback every 10 ms */
void Robot_ControlLoop(void)
{
    /* 1. Read encoders */
    Encoder_Update(&left_enc);
    Encoder_Update(&right_enc);

    float v_left  = Encoder_GetLinearVelocity(&left_enc,  WHEEL_RADIUS);
    float v_right = Encoder_GetLinearVelocity(&right_enc, WHEEL_RADIUS);

    /* 2. Update odometry */
    DiffDrive_UpdateOdometry(&robot, v_left, v_right, CONTROL_DT_S);

    /* 3. Inverse kinematics — desired → wheel setpoints */
    float sp_left, sp_right;
    DiffDrive_VelToWheels(&robot, g_target_v, g_target_omega,
                          &sp_left, &sp_right);

    /* sp_* are percent [-100..100]; convert to m/s for PID */
    float sp_left_mps  = sp_left  * MAX_SPEED_MPS / 100.0f;
    float sp_right_mps = sp_right * MAX_SPEED_MPS / 100.0f;

    /* 4. Velocity PID */
    float out_left  = PID_Compute(&left_pid,  sp_left_mps,  v_left);
    float out_right = PID_Compute(&right_pid, sp_right_mps, v_right);

    /* 5. Drive motors */
    Motor_SetSpeed(&left_motor,  out_left);
    Motor_SetSpeed(&right_motor, out_right);
}

/* Wire this into HAL_TIM_PeriodElapsedCallback in your main.c */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6) {
        Robot_ControlLoop();
    }
}
